### register user
POST http://localhost:3000/api/users/auth/register
Content-Type: application/json

{
    "username":"ahmad2",
    "email":"ahmad2@example.com",
    "password":"fortesting"
}

### login User
POST http://localhost:3000/api/users/auth/login
Content-Type: application/json

{
    "email":"ahmad98@example.com",
    "password":"fortesting"
}
### Get current User
GET http://localhost:3000/api/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlclR5cGUiOiJhZG1pbiIsImlhdCI6MTc2Njg0NTQ0NywiZXhwIjoxNzY2OTMxODQ3fQ.HluHxkjeec2nzvqvbfNLgqWrvWQNIdbrNo4NBE9yr64

### get all user
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NC


### Forget Password
POST http://localhost:5000/api/users/forgot-password
Content-Type: application/json

{
    "email":"ahmad98@example.com"
}

### Reset Password
POST http://localhost:5000/api/users/reset-password
Content-Type: application/json

{   "userId": 3,
    "resetPasswordToken":"042c7c2e8043b321116cd1ed30fd3460f8169fef012c78e5215a8159d9082afd",
    "newPassword": "fortesting"
}

